# Generated by Django 3.1 on 2020-08-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200828_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Games',
            new_name='Post_Game',
        ),
    ]
