# Generated by Django 3.1 on 2020-08-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200828_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_game',
            name='game_img',
            field=models.ImageField(blank=True, upload_to='clients/media', verbose_name='Foto do Game'),
        ),
    ]
