# Generated by Django 3.1 on 2020-08-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_post_game_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_game',
            name='game_img',
            field=models.ImageField(upload_to='clients/media', verbose_name='Foto do Game'),
        ),
    ]
