# Generated by Django 3.1 on 2020-08-28 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200828_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=50, verbose_name='Nome do jogo')),
                ('release_year', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Ano de Lançamento')),
                ('text', models.TextField(verbose_name='Resumo do jogo')),
                ('date_publish', models.DateField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('game_img', models.ImageField(upload_to='media', verbose_name='Foto do Game')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Foto do perfil'),
        ),
        migrations.DeleteModel(
            name='Post_Game',
        ),
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
